config/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('reset/', views.ResetView.as_view(), name='reset'),

    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.QuillPostListView.as_view(), name='quill-post-list'),
    path('create/', views.QuillPostCreateView.as_view(), name='quill-post-create'),
    path('create/normal/', views.QuillFieldFormView.as_view(), name='quill-post-create-normal'),
    path('create/normal/html/', views.QuillFieldFormHtmlInitialView.as_view(), name='quill-post-create-normal-html'),
    path('create/normal/text/', views.QuillFieldFormTextInitialView.as_view(), name='quill-post-create-normal-text'),
    path('<int:pk>/', views.QuillPostDetailView.as_view(), name='quill-post-detail'),
    path('<int:pk>/update/', views.QuillPostUpdateView.as_view(), name='quill-post-update'),
]

posts/models.py
from django.db import models
from django.urls import reverse

from django_quill.fields import QuillField


class QuillPost(models.Model):
    content = QuillField()

    class Meta:
        ordering = ['-pk']

    def get_absolute_url(self):
        return reverse('posts:quill-post-detail', args=[self.pk])

config/forms.py
from django import forms

from django_quill.forms import QuillFormField


class QuillForm(forms.Form):
    quill = QuillFormField()

posts/forms.py
from django import forms

from django_quill.forms import QuillFormField
from .models import QuillPost


class QuillFieldForm(forms.Form):
    content = QuillFormField()

    def save(self):
        return QuillPost.objects.create(content=self.cleaned_data['content'])


class QuillPostForm(forms.ModelForm):
    class Meta:
        model = QuillPost
        fields = (
            'content',
        )

config/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView

from posts.forms import QuillPostForm, QuillFieldForm
from posts.models import QuillPost


class IndexView(CreateView):
    template_name = 'index.html'
    form_class = QuillPostForm
    success_url = reverse_lazy('posts:quill-post-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['normal_form'] = QuillFieldForm()
        return context


class ResetView(View):
    def post(self, request):
        QuillPost.objects.all().delete()
        return redirect(reverse('posts:quill-post-list'))

posts/views.py
from django.urls import reverse
from django.views.generic import ListView, UpdateView, DetailView, FormView, CreateView

from .forms import QuillFieldForm, QuillPostForm
from .models import QuillPost

INITIAL_IMG = 'https://picsum.photos/300/200'


class QuillPostListView(ListView):
    model = QuillPost


class QuillPostCreateView(CreateView):
    form_class = QuillPostForm
    template_name = 'posts/quillpost_create.html'


class QuillPostDetailView(DetailView):
    model = QuillPost


class QuillPostUpdateView(UpdateView):
    model = QuillPost
    fields = ['content']


# NormalForm
class QuillFieldFormView(FormView):
    form_class = QuillFieldForm
    template_name = 'posts/quillpost_normal_form.html'

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:quill-post-detail', args=(self.object.pk,))


class QuillFieldFormHtmlInitialView(QuillFieldFormView):
    initial = {
        'content': f'<h1>django-quill-editor</h1><br>'
                   f'<img src="{INITIAL_IMG}">',
    }


class QuillFieldFormTextInitialView(QuillFieldFormView):
    initial = {
        'content': 'django-quill-editor makes Quill.js easy to use on Django Forms and admin sites',
    }

templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- django-quill-editor Media -->
    {% include 'django_quill/media.html' %}

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>メモッター</title>
</head>
<body>
    <div id="wrap">
        <nav class="navbar navbar-expand navbar-dark bg-primary mb-2">
            <a href="{% url 'index' %}" class="navbar-brand">TOP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="w-100">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'posts:quill-post-list' %}" class="nav-link">リスト</a>
                    </li>
                    <li class="nav-item mr-auto">
                        <a href="{% url 'admin:index' %}" class="nav-link" target="_blank">管理者サイト</a>
                    </li>
                   </li>
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <footer class="mt-2 text-center"> Yasuto © 2021</a></footer>

        {% block script %}
        {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    {{ form.media }}
</head>
    <div class="container-fluid">
        <h2><b>メモッター</b></h2>
        <ul>
            <li><b>あなたがメモしたいことをのせてください。</b></li>
            <li><b>記事をコピペでかまいません。</b></li>
        </ul>
        <hr>
<!-- Template -->
<form action="" method="POST">{% csrf_token %}
    {{ form.content }}
    <button type="submit" class="btn btn-primary btn-block mt-1">Create</button>

</form>

 
    </div>
{% endblock %}

templates/posts/base_posts.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row mb-2">
            <div class="col-12 col-md-3 col-lg-3">
                <h3>{% block title %}title{% endblock %}</h3>
            </div>
            <div class="col-12 col-md-9 col-lg-9">
                <div class="d-flex justify-content-end">
                    <form action="{% url 'reset' %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-danger mr-4">Delete all posts</button>
                    </form>
                    <a href="{% url 'posts:quill-post-create-normal' %}" class="btn btn-primary mr-1">Form</a>
                    <a href="{% url 'posts:quill-post-create' %}" class="btn btn-primary mr-1">ModelForm</a>
                    <a href="{% url 'posts:quill-post-create-normal-html' %}" class="btn btn-primary mr-1">Form (Initial HTML)</a>
                    <a href="{% url 'posts:quill-post-create-normal-text' %}" class="btn btn-primary mr-1">Form (Initial Text)</a>
                </div>
            </div>
        </div>
        {% block posts_content %}
        {% endblock %}
    </div>
{% endblock %}

templates/posts/quillpost.html
<div class="card">
    <div class="card-body">
        <div>
            {{ post.content.html|safe }}
        </div>
        <a href="{% url 'posts:quill-post-update' pk=post.pk %}" class="btn btn-primary btn-sm">EDIT</a>
    </div>
</div>

templates/posts/quillpost_create.html
{% extends 'posts/base_posts.html' %}

{% block title %}Post Create (ModelForm){% endblock %}
{% block posts_content %}
    <form action="" method="POST">{% csrf_token %}
        {{ form.content }}
        <button type="submit" class="btn btn-primary btn-block mt-1">Create</button>
    </form>
{% endblock %}

templates/posts/quillpost_detail.html
{% extends 'posts/base_posts.html' %}

{% block title %}Post Detail {% endblock %}
{% block posts_content %}
    {% include 'posts/quillpost.html' with post=object %}
{% endblock %}

templates/posts/quillpost_form.html
{% extends 'posts/base_posts.html' %}

{% block title %}Post Update (pk: {{ object.pk }}){% endblock %}
{% block posts_content %}
    <div><a href="{% url 'posts:quill-post-detail' pk=object.pk %}" class="btn btn-primary btn-sm">◀ Back to Detail</a></div>
    <div class="mt-2">
        <form action="" method="POST">{% csrf_token %}
            {{ form.content }}
            <button type="submit" class="btn btn-primary btn-block mt-1">Update Post</button>
        </form>
    </div>
{% endblock %}

templates/posts/quillpost_list.html
{% extends 'posts/base_posts.html' %}

{% block title %}Post List{% endblock %}
{% block posts_content %}
    <div class="row">
        <div class="col">
            {% if object_list %}
                {% for post in object_list %}
                    {% include 'posts/quillpost.html' with post=post %}
                    {% if not forloop.last %}
                        <hr>{% endif %}
                {% endfor %}
            {% else %}
                <p>There is no post.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/posts/quillpost_normal_form.html
{% extends 'posts/base_posts.html' %}

{% block title %}Post Create (NormalForm){% endblock %}
{% block posts_content %}
    <form action="" method="POST">{% csrf_token %}
        {{ form.content }}
        <button type="submit" class="btn btn-primary btn-block mt-1">Create</button>
    </form>
{% endblock %}